### ISSUE TITLE
Erro no arquivo do banco de dados

### ISSUE THREAD

**Issue by vpozzebon** [SappiensFramework/Sappiens#1]
O colaborador Fhagner relatou problemas no arquivo SQL que consta em /Sappiens/_doc/sql

Realmente o arquivo está bugado e temporariamente, peço que baixem o arquivo disponível em http://goo.gl/Xxoa14

**Comment by vpozzebon** [comment]
Corrigodo o arquivo SQL problemático.

**Comment by jfranciscos4** [comment]
:+1:
